from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Mapping, Sequence
from pathlib import Path

from source_profiles import REACHABILITY_RANK, load_profiles

HEADER = """# Source Catalog

> Generated by `scripts/build_source_catalog.py`. Edit source profiles or the
> reviewed reachability snapshot, then regenerate this file.

The source catalog is a seed registry, not a closed allowlist.
Do not reject a source solely because it is absent from the catalog.
Use uncataloged sources when the question requires them and they pass validation.
Record uncataloged sources with the same fields, access status, provenance, fallback peers, and evidence level.

This catalog records source-level routing facts checked in the supplied audit
reports dated `2026-08-01`. A failed request is a point-in-time observation,
not proof of permanent closure. `Not recorded in audit` identifies a fact the
seed audit did not establish; it is not an invented negative finding.

Catalog ratings are route priors scoped to each record's stated best uses.
Authority is claim-scoped and remains separate from current reachability and
practical utility. Runtime `conclusion_evidence` must be calculated for the
actual claim after retrieving evidence.
Do not copy a catalog route prior into a runtime ledger as a claim grade.

Approved reviewed reachability statuses: `reachable`, `reachable-limited`,
`login-required`, `paywalled`, `anti-bot`, `temporarily-unreachable`, `moved`,
`broken-link`, and `unverified`.

Evidence dimensions are separate: provenance authority identifies the
publisher's claim scope; access observation evidence records confidence in the
observed access state; completed-workflow evidence records support for the
specific route producing a record or document; and stable field/API evidence
records support for a repeatable field or API contract. Do not promote one
dimension into another.

Treat company websites as first-party subject evidence only for the publisher's
own statements, actions, products, policies, prices, filings, and quotations.
Do not treat a company's evaluative claims as independent proof. Aggregators,
media, mirrors, social platforms, and report indexes remain discovery routes
unless the narrow verified-mirror exception applies.
Use aggregators, media, social platforms, and report indexes for discovery only; conclusions must cite the original publisher whenever the original can be identified.

One failed request never proves permanent closure. Continue through applicable
same-function fallbacks, then adjacent categories, and record every attempted
route before reporting a source gap.

Only a function's declared same-function fallbacks are executable route
transitions. Adjacent alternatives are guidance-only sources with a related
topic, producer, jurisdiction, or methodology; they cannot substitute for the
requested claim without an explicit scope change.
"""


def load_snapshot(path: Path, known_source_ids: set[str]) -> dict[str, dict[str, object]]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"{path}: expected a JSON object")

    unknown_source_ids = sorted(set(payload) - known_source_ids)
    if unknown_source_ids:
        raise ValueError(f"{path}: unknown source IDs: {', '.join(unknown_source_ids)}")

    snapshot: dict[str, dict[str, object]] = {}
    for source_id, observation in payload.items():
        if not isinstance(observation, dict):
            raise ValueError(f"{path}: {source_id}: expected an observation object")
        status = observation.get("status")
        if status not in REACHABILITY_RANK:
            raise ValueError(f"{path}: {source_id}: unsupported status: {status}")
        snapshot[source_id] = observation
    return snapshot


def render_catalog(
    profiles: Sequence[Mapping[str, object]],
    snapshot: Mapping[str, Mapping[str, object]],
    site_guides_dir: Path,
) -> str:
    sections = [HEADER.rstrip()]
    for profile in sorted(profiles, key=lambda item: _require_str(item, "id")):
        sections.append(_render_profile(profile, snapshot, site_guides_dir))
    return "\n\n".join(sections) + "\n"


def _render_profile(
    profile: Mapping[str, object],
    snapshot: Mapping[str, Mapping[str, object]],
    site_guides_dir: Path,
) -> str:
    source_id = _require_str(profile, "id")
    name = _require_str(profile, "name")
    aliases = _require_str_list(profile, "aliases")
    publisher_type = _require_str(profile, "publisher_type")
    official_domains = _require_str_list(profile, "official_domains")
    authority = _require_mapping(profile, "authority")
    functions = _require_mapping_list(profile, "functions")
    profile_access = _require_mapping(profile, "access")
    reviewed_access = snapshot.get(source_id, profile_access)

    lines = [
        f"## `{source_id}` - {name}",
        "",
        f"- Aliases/origins: {', '.join(f'`{alias}`' for alias in aliases)}",
        f"- Publisher type: `{publisher_type}`",
        f"- Official domains: {', '.join(f'`{domain}`' for domain in official_domains)}",
        f"- Provenance authority: `{_require_str(authority, 'level')}` - "
        f"{_require_str(authority, 'scope')}",
    ]

    for function in functions:
        function_id = _require_str(function, "id")
        lines.extend(
            (
                f"- Function: `{function_id}`",
                f"  - Authority: `{_require_str(function, 'authority')}`",
                f"  - Utility: `{_require_str(function, 'utility')}`",
                f"  - Completed workflow evidence: `{_require_str(function, 'workflow_evidence')}`",
                f"  - Stable field/API evidence: "
                f"`{_require_str(function, 'field_contract_evidence')}`",
                f"  - Direct links: {_render_direct_links(function)}",
                f"  - Search example: `{_require_search_example(function)}`",
                f"  - Same-function fallbacks: {_render_fallbacks(function)}",
            )
        )
        adjacent = _optional_str_list(function, "adjacent_alternatives")
        if adjacent:
            lines.append(
                "  - Adjacent alternatives (not executable fallbacks): "
                + ", ".join(f"`{alternative}`" for alternative in adjacent)
            )
        issuer_copy = function.get("issuer_copy_evidence")
        if isinstance(issuer_copy, Mapping):
            lines.extend(
                (
                    "  - Verified issuer copy (not primary citation): "
                    f"HKEX document `{_require_str(issuer_copy, 'hkex_document_id')}`",
                    f"  - Issuer copy URL: <{_require_str(issuer_copy, 'issuer_copy_url')}>",
                    f"  - Issuer copy SHA-256: `{_require_str(issuer_copy, 'sha256')}`",
                )
            )

    lines.extend(
        (
            f"- Current status: `{_require_str(reviewed_access, 'status')}`",
            f"- Last checked: `{_require_str(reviewed_access, 'last_checked')}`",
            f"- Access limitations: {_require_str(reviewed_access, 'limitation')}",
            f"- Access observation evidence: `{_require_str(reviewed_access, 'evidence_level')}`",
            f"- Site guide: {_render_site_guide(source_id, site_guides_dir)}",
        )
    )
    return "\n".join(lines)


def _render_direct_links(function: Mapping[str, object]) -> str:
    direct_urls = _require_mapping_list(function, "direct_urls")
    return ", ".join(
        f"[{_require_str(route, 'kind')}](<{_require_str(route, 'url')}>)" for route in direct_urls
    )


def _require_search_example(function: Mapping[str, object]) -> str:
    search = _require_mapping(function, "search")
    return _require_str(search, "example_query")


def _render_fallbacks(function: Mapping[str, object]) -> str:
    fallbacks = _require_str_list(function, "fallbacks")
    if not fallbacks:
        return "None"
    return ", ".join(f"`{fallback}`" for fallback in fallbacks)


def _render_site_guide(source_id: str, site_guides_dir: Path) -> str:
    guide = site_guides_dir / f"{source_id}.md"
    if not guide.is_file():
        return "None"
    return f"[`{source_id}` guide](site-guides/{source_id}.md)"


def _require_mapping(mapping: Mapping[str, object], key: str) -> Mapping[str, object]:
    value = mapping.get(key)
    if not isinstance(value, Mapping):
        raise ValueError(f"missing mapping field: {key}")
    return value


def _require_mapping_list(
    mapping: Mapping[str, object],
    key: str,
) -> list[Mapping[str, object]]:
    value = mapping.get(key)
    if not isinstance(value, list) or not all(isinstance(item, Mapping) for item in value):
        raise ValueError(f"missing mapping-list field: {key}")
    return value


def _require_str(mapping: Mapping[str, object], key: str) -> str:
    value = mapping.get(key)
    if not isinstance(value, str):
        raise ValueError(f"missing string field: {key}")
    return value


def _require_str_list(mapping: Mapping[str, object], key: str) -> list[str]:
    value = mapping.get(key)
    if not isinstance(value, list) or not all(isinstance(item, str) for item in value):
        raise ValueError(f"missing string-list field: {key}")
    return value


def _optional_str_list(mapping: Mapping[str, object], key: str) -> list[str]:
    value = mapping.get(key)
    if value is None:
        return []
    if not isinstance(value, list) or not all(isinstance(item, str) for item in value):
        raise ValueError(f"invalid optional string-list field: {key}")
    return value


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build the deterministic source catalog.")
    parser.add_argument("--profiles", required=True, type=Path)
    parser.add_argument("--snapshot", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--check", action="store_true")
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    schema_path = args.profiles.parent / "source-profile.schema.json"
    profiles = load_profiles(args.profiles, schema_path)
    known_source_ids = {_require_str(profile, "id") for profile in profiles}
    snapshot = load_snapshot(args.snapshot, known_source_ids)
    rendered = render_catalog(profiles, snapshot, args.profiles.parent / "site-guides")

    if args.check:
        if not args.output.is_file() or args.output.read_text(encoding="utf-8") != rendered:
            print(f"source catalog is out of date: {args.output}", file=sys.stderr)
            return 1
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
